create table
  public.global_inventory (
    num_green_ml integer not null default 0,
    gold integer not null default 0,
    num_red_ml integer not null default 0,
    num_blue_ml integer not null default 0,
    num_dark_ml integer not null default 0,
    constraint global_inventory_pkey primary key (gold)
  ) tablespace pg_default;

INSERT INTO global_inventory (num_green_ml, gold, num_red_ml, num_blue_ml, num_dark_ml) VALUES (0, 100, 0, 0, 0);

create table
  public.potions (
    item_sku text not null,
    red integer not null,
    green integer null,
    blue integer null,
    dark integer null,
    inventory integer null,
    price integer null,
    constraint potions_pkey primary key (item_sku)
  ) tablespace pg_default;

INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Green_Potion', 0, 100, 0, 0, 0, 55);
INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Purple_Potion', 50, 0, 50, 0, 0, 55);
INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Blue_Potion', 0, 0, 100, 0, 0, 55);
INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Pink_Potion', 50, 0, 0, 50, 0, 55);
INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Orange_Potion', 50, 25, 25, 0, 0, 55);
INSERT INTO potions (item_sku, red, green, blue, dark, inventory, price) VALUES ('Red_Potion', 100, 0, 0, 0, 0, 55);

create table
  public.carts (
    cart_id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    customer_name text not null,
    visit_id integer null,
    constraint cart_pkey primary key (cart_id),
    constraint cart_cart_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id integer not null,
    item_sku text not null,
    quantity integer not null,
    price integer not null,
    constraint cart_items_pkey primary key (cart_id, item_sku),
    constraint public_cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id) on delete cascade,
    constraint public_cart_items_item_sku_fkey foreign key (item_sku) references potions (item_sku)
  ) tablespace pg_default;
